### ISSUE TITLE
clarify how to write custom metrics

### ISSUE THREAD

**Issue by ibotty** [discourse/prometheus_exporter#1]
Do I understand the documentation correctly, that the only way to track custom metrics is to collect them within the prometheus_exporter process?

If not, can you include a few notes in the documentation on how to, say, observe something when accessing a route.

**Comment by SamSaffron** [comment]
Absolutely all for improving the doco, can you describe what you are trying
to do exactly?

**Comment by ibotty** [comment]
I'd like to observe request-specific metrics. On some multi-page forms, I want to track, how long it took users to get to the next page. Things I can easily access from my controller (I am using rails for that example).

Reading the source for the existing instrumentation, I will have to use `PrometheusExporter::Client::send_json` to send a simple dict to the prometheus_exporter process. That is simple enough, but different from the usual prometheus way where you usually collect in the same process. Does `send_json` block? If so, there is quiet some reinventing the wheel to do.

**Comment by SamSaffron** [comment]
Oh you can run this in a single process if you want, but how are you
running your web? A single process puma?

**Comment by SamSaffron** [comment]
Note send json does not block and is batched

**Comment by ibotty** [comment]
I am usually running multi-process puma (that's why I decided to use that prometheus lib).

I get from your comments, that I understood the way to use custom metrics. I might contribute an example when I get around implementing it in this app. No ETA though.

**Comment by SamSaffron** [comment]
OK I just updated the readme here to clarify and reviewed all the examples. I think I covered your concerns. 

Feel free to submit any extra PRs to improve the documentation further 

https://github.com/discourse/prometheus_exporter/blob/master/README.md

**Comment by ibotty** [comment]
Oh, yes that answers my question completly. It also clarifies, that send_json is not needed. Good to know!

Thank you!
