### ISSUE TITLE
allow specification of exporter bind address

### ISSUE THREAD

**Issue by and0x000** [discourse/prometheus_exporter#101]
I think it would be a good idea, to allow the specification of an address to which [PrometheusExporter::WebServer](https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/server/web_server.rb#L39) should bind to.

See [WEBrick::HTTPServer -> :BindAddress](https://ruby-doc.org/stdlib-2.7.0/libdoc/webrick/rdoc/WEBrick/HTTPServer.html)

Going a step further, binding to `localhost` only should probably become the default behavior. This is the way, several other pieces of software do it to avoid unintended insecure configurations.

**Comment by SamSaffron** [comment]
I am fine for starters for this to be configurable and documented, care to post a PR?
