### ISSUE TITLE
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394

### ISSUE THREAD

**Issue by arunshan** [discourse/prometheus_exporter#11]
When I apply the middleware to my existing rails app I get this error

```Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394```

My app is running on port 3000 and is there a way to change PORT for `/metrics` ?

**Comment by SamSaffron** [comment]
The collector expects to run on a dedicated port, did you run the collector with `bundle exec prometheus_exporter`

**Comment by arunshan** [comment]
That did it. Running `bundle exec prometheus_exporter`. Thank you.
