### ISSUE TITLE
Prometheus push gateway

### ISSUE THREAD

**Issue by konfortes** [discourse/prometheus_exporter#113]
Hey guys, 
Any plan to add push gateway client any time soon?

**Comment by SamSaffron** [comment]
No specific plans, feels a bit out of scope to me. Maybe a section in the README explaining how you would wire it? 

Essentially exporter is already a push gateway of sorts, adding yet another one to the mix does not really make sense to me. 

Can you explain what problem you are looking to solve?

**Comment by konfortes** [comment]
I might be missing something, can you explain the sentence: 
> exporter is already a push gateway of sorts

The problem I'm currently looking to solve is how to instrument a Kafka consumer that doesn't handle any HTTP and later on, short-lived jobs.

see: [prometheus/client_ruby](https://github.com/prometheus/client_ruby#pushgateway)

**Comment by SamSaffron** [comment]
Sure, in general prom exporter is designed so you run a single long running process which is the process that runs the exporter. 

Then various ruby processes in the container ship information to it. 

Short lived jobs would ship metrics to this long lived exporter job. 

See the multi process mode in the README.

**Comment by konfortes** [comment]
Cool! that will do
thanks
