### ISSUE TITLE
Documentation, list of metric series

### ISSUE THREAD

**Issue by wolfgangrittner** [discourse/prometheus_exporter#115]
Hey there, we're using prometheus-exporter and it's great so far! Thank you for that!
What we are missing, and what I could not really find was a list of metrics series prometheus-exporter itself and all the various integrations (sidekiq, puma etc.) create and report to. Skimming through the code works, but gets tedious.
Would you be open for a PR that tries to add an extensive list of series created and used by the various parts of prometheus-exporter to the README? Or would you want that to go somewhere else? Or does that exist already after all and I totally missed it? 😬

**Comment by SamSaffron** [comment]
> Would you be open for a PR that tries to add an extensive list of series created and used by the various parts of prometheus-exporter to the README?

Absolutely! That would be delightful.

**Comment by wolfgangrittner** [comment]
Guess this can be closed?

**Comment by SamSaffron** [comment]
sure can, thanks!!
