### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by siebertm** [discourse/prometheus_exporter#14]
The current release is pretty old (in terms of this young software), maybe you should cut a 2.0? (I'd see the merge of #12 as a major change)

**Comment by SamSaffron** [comment]
I am not against cutting this ... but it looks like tests are failing due to #12 @peterbourgon  ... also we have to document this better and explain at least somewhere what happened.

**Comment by SamSaffron** [comment]
OK 0.2.0 is now released! thanks heaps @ezkl  !
