### ISSUE TITLE
Extremely bad performance of exporter server

### ISSUE THREAD

**Issue by gucki** [discourse/prometheus_exporter#146]
I'm currently performing load tests an an application, which writes metrics to a prometheus exporter instance in the same docker stack (same machine). The application often can't write the metrics because of a connection timeout to the prometheus exporter instance. Looking at the exporter I see it's using only about 3% cpu and not processing a lot of events:

    10.0.0.4 - - [08/Dec/2020:13:07:02 CET] "GET /metrics HTTP/1.1" 200 4584
    - -> /metrics
    10.0.2.12 - - [08/Dec/2020:13:06:49 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:07:02 CET] "POST /send-metrics HTTP/1.1" 200 0
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:53 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:53 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:49 CET] "POST /send-metrics HTTP/1.1" 200 0
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:50 CET] "POST /send-metrics HTTP/1.1" 200 0
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:53 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:51 CET] "POST /send-metrics HTTP/1.1" 200 0
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:49 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:53 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    10.0.2.12 - - [08/Dec/2020:13:06:50 CET] "POST /send-metrics HTTP/1.1" 200 2
    10.0.2.12 - - [08/Dec/2020:13:06:57 CET] "POST /send-metrics HTTP/1.1" 200 2
    - -> /send-metrics
    - -> /send-metrics

The /send-metrics requests seem to be processed quite fast, but the /metrics endpoint is really slow (4500ms?). Why is that? The cpu usage of the exporter is only 3%. I noticed it's using webrick, which isn't the most performant webserver? Any ideas what's wrong? Is it possible to switch to puma? Would it help? Thank you.

**Comment by SamSaffron** [comment]
>  the /metrics endpoint is really slow (4500ms?). Why is that?

How many metrics do you have? I could imagine this could be the case if you have 10s of thousands of metrics.

**Comment by gucki** [comment]
@SamSaffron No, not really a lot. The logs of the exporter server show around 20-30 POST /send-metrics requests per second. max_queue_size in the client is set to 100. 

This is what our Tracker class looks like:

    def time(action, labels = {}, &block)
      return block.call unless profiling_enabled?
      result = nil
      exception = nil
      time = Benchmark.realtime do
        result = block.call
      rescue StandardError => e
        exception = e
      end
      histogram = client.register(:histogram, "#{name}_#{action}", description, buckets: settings.buckets)
      histogram.observe(time, labels)
      logger.debug("added timing of #{action} with #{time.round(3)}s (#{labels})")
      raise(exception) if exception
      result
    end

    def client
      @client ||= PrometheusExporter::Client.new(host: settings.host, max_queue_size: settings.max_queue_size)
    end

And the actual invocation is like:

      Tracker.time("some-action", tag: "test") do
        ...
      end

Could the problem be that we initialize a new instance of the client and register the metric (histogram) for each value we track?

**Comment by SamSaffron** [comment]
```
 histogram = client.register(:histogram, "#{name}_#{action}", description, buckets: settings.buckets)
  histogram.observe(time, labels)
```

Yeah this looks sus to me.  You only want to register this new metric once, not every time you measure something. Maybe try wrapping with a "lookup histogram or register a new one" type method?

**Comment by gucki** [comment]
Thanks, we'll give it a try and I'll reopen this issue in case it doesn't fix our problems.
