### ISSUE TITLE
Delayed Jobs pending and pending gauges per queue

### ISSUE THREAD

**Issue by blackjid** [discourse/prometheus_exporter#147]
Hi!, I've just updated the gem to get the `pending` and `enqueued` metrics for delayed jobs which are very nice to scale the workers and to have better visibility.

I run prometheus_exporter per delayed job worker (as a sidecar in the same pod in kubernetes).

If I run a prom ql query like `ruby_delayed_jobs_equeued` I get the total number of jobs enqueued across all my queues, and also one metric per worker.

So I have two questions
1. How do you manage a global metric as `ruby_delayed_jobs_equeued` when is scraped from multiple containers?? Do you just have to know that you cannot do `sum(ruby_delayed_jobs_equeued)` for example??
2. Would it be possible to improve the metrics by adding the queue labels?? Do you think it might be consider like a high cardinality?
   It could done with somehting like
   ```
   pending = Delayed::Job.where(attempts: 0, locked_at: nil).group(:queue).count
   enqueued = Delayed::Job.group(:queue).count
   ```

**Comment by SamSaffron** [comment]
Sure I am open to adding labels. Having something you can not sum does really suck, but I can not think of any way around it :( 

Feel free to do a PR for the label improvements, I do not use delayed job so it is hard for me to support all the fidelity you need, this is going to need to come from the community
