### ISSUE TITLE
Minimum compatible ruby version?

### ISSUE THREAD

**Issue by JKolios** [discourse/prometheus_exporter#15]
Hi. While trying to run `bin/bundle exec  prometheus_exporter` in a Ruby v.2.2.3 project, I encountered the following SyntaxError.
```
SyntaxError: /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/web_server.rb:142: syntax error, unexpected <<, expecting keyword_end
      <<~TEXT
        ^
  /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server.rb:7:in `require_relative'
  /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server.rb:7:in `<top (required)>'
  /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prometheus_exporter-0.1.13/bin/prometheus_exporter:6:in `require_relative'
  /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prometheus_exporter-0.1.13/bin/prometheus_exporter:6:in `<top (required)>'
  /Users/jason/.rbenv/versions/2.2.3/bin/prometheus_exporter:23:in `load'
  /Users/jason/.rbenv/versions/2.2.3/bin/prometheus_exporter:23:in `<top (required)>'
```

It looks like the gem is using syntax features which were added in Ruby v2.3.0, like the ["squiggly HEREDOC syntax"](https://github.com/ruby/ruby/blob/d40ea2afa6ff5a6e5befcf342fb7b6dc58796b20/ChangeLog#L1177). The documentation doesn't mention a minimum Ruby version. Is there a version of the gem which supports Ruby < 2.3.0? If not, can you add a mention of this in the README?

**Comment by SamSaffron** [comment]
2.2.0 is EOL at 2018-03-31, since this is a reasonably new project I think setting minimum to 2.3 and up is fine, can you do a PR for that, another breaking change for 1.0 release

**Comment by SamSaffron** [comment]
OK, just added a note about this!
