### ISSUE TITLE
Register multiple metrics at once

### ISSUE THREAD

**Issue by tarko** [discourse/prometheus_exporter#152]
Would you be open to a pull request that would enable registering lots of metrics at once?

Something along the lines of:

```
    def register_metric(*metrics)
      @mutex.synchronize do
        metrics.each do |metric|
         @metrics[metric.name] = metric
       end
      end
    end
```

**Comment by SamSaffron** [comment]
I follow, but I am not sure I would like to increase the api surface here when it is so easy for you to make your own little helper.
