### ISSUE TITLE
Canceled statement due to statement timeout not reported

### ISSUE THREAD

**Issue by gbxl** [discourse/prometheus_exporter#158]
When a query is canceled due to reaching statement timeout in Postgres, the duration isn't shown in the Prometheus metrics.
When I observe `PG::QueryCanceled: ERROR:  canceling statement due to statement timeout` in my logs, I cannot find an equivalent long time in `http_sql_duration_seconds` on my metrics endpoint.
I would expect the middleware to report timing on all queries, even those canceled.
After a cursory read of the code, I'd imagine https://github.com/discourse/prometheus_exporter/blob/a7bea7aeb26acbe934223de2e218d929cd1bf976/lib/prometheus_exporter/middleware.rb#L38 is supposed to always report, but I could be mistaken.

Happy to help with debugging/fixing if someone can help me confirm this is an issue :)

**Comment by SamSaffron** [comment]
Yeah sounds like a legit issue, very much appreciate a fix here.

**Comment by gbxl** [comment]
Sounds good. Had a quick look at it, don't see anything obvious. My guess is that PG might somehow move to one of the methods that aren't passed to `MethodProfiler.patch` when hitting a timeout. Not super confortable with C code (PG gem). If you have any pointers that'd be much appreciated :)

**Comment by gbxl** [comment]
After digging further, I was able to verify that the collector does receive a call when a statement times out.
For posterity, here is how I tested it:

in a random controller:
```
    c = PG.connect options: "-c statement_timeout=1s"
    puts "-----------------------------------------------------------------------------"
    puts "ABOUT TO TIMEOUT"
    puts "-----------------------------------------------------------------------------"
    c.exec("select pg_sleep(2)")
```

While adding some outputs to `lib/prometheus_exporter/server/web_collector.rb` in the ` if sql = timings["sql"]` condition of `observe`.
