### ISSUE TITLE
Creating default label

### ISSUE THREAD

**Issue by yosiat** [discourse/prometheus_exporter#17]
Hi,

I want to add default label to all metrics - "node_name", how can I achieve this?
If this not supported, I think new option like:

```
PrometheusExporter::Metric::Base.default_labels = { "node_name" => "..." }
```

Wdyt? would you like to accept PR for this?

**Comment by SamSaffron** [comment]
totally fine with me, just be sure to add a test

**Comment by yosiat** [comment]
Done in - https://github.com/discourse/prometheus_exporter/pull/19
