### ISSUE TITLE
[Feature Request] - Rpush instrumentation

### ISSUE THREAD

**Issue by mhenrixon** [discourse/prometheus_exporter#171]
My current company is using RPush and RPush has a plugin system. I found the following: https://github.com/rpush/rpush-plugin-statsd/blob/master/lib/rpush/plugin/statsd.rb

Any suggestions for how I can achieve something similar using prometheus_exporter?

**Comment by maxsz** [comment]
Here you go https://github.com/equinux/rpush-plugin-prometheus-exporter

**Comment by mhenrixon** [comment]
Well, that shows how to do it :)
