### ISSUE TITLE
mysql2 support

### ISSUE THREAD

**Issue by errm** [discourse/prometheus_exporter#18]
I was thinking about adding support for mysql2 and perhaps also dalli (memcache).

Would you accept a PR?

**Comment by SamSaffron** [comment]
possibly, what exactly are you looking at instrumenting?

**Comment by errm** [comment]
Just to replicate the SQL metrics when using mysql rather than postgres ...

**Comment by SamSaffron** [comment]
sure this should be fine, give it a shot.

**Comment by lcasassa** [comment]
@errm any progress with this? looking forward :)

**Comment by errm** [comment]
I didn't work on this since I decided to use another solution https://gitlab.com/gitlab-org/prometheus-client-mmap for some reasons...

I don't think it would be difficult to do though, I think you could just add the extra profiling just here for MySQL2 https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/middleware.rb#L17-L20
