### ISSUE TITLE
feature request: delayed_job instrumentation

### ISSUE THREAD

**Issue by ibotty** [discourse/prometheus_exporter#2]
It would be great to also collect delayed_job metrics.

**Comment by SamSaffron** [comment]
Sure, PR totally welcome here for an out-of-the-box solution like sidekiq has

**Comment by mbobin** [comment]
I can have a crack at it using lifecycle callbacks around(:invoke_job). Is that OK?

**Comment by SamSaffron** [comment]
Yes that seems like the way to go!

**Comment by SamSaffron** [comment]
cool, this is complete now!
