### ISSUE TITLE
Gem is not updated with SidekiqStats

### ISSUE THREAD

**Issue by nezihtkadioglu** [discourse/prometheus_exporter#203]
Hello,
It would seem that the latest tag (v1.0.0) was created 2 days before the `SidekiqStats` feature addition, could we bump the version with the newest additions?

**Comment by SamSaffron** [comment]
Sure, @CvX will push another version of the gem over the next few days.

**Comment by CvX** [comment]
Version 1.0.1 is out! 🚀
