### ISSUE TITLE
Rename http_duration_seconds metric to http_request_duration_seconds

### ISSUE THREAD

**Issue by MaximeD** [discourse/prometheus_exporter#210]
Hello,
Same thing as in #182 , we noticed that [prometheus](https://prometheus.io/docs/practices/naming/#metric-names) suggest to have `http_request_duration_seconds` instead of just `http_duration_seconds`.

Would you be open to this renaming, and bumping a new release with this breaking change?

Thank you!

**Comment by SamSaffron** [comment]
Yes, sounds like a good rename, but we are going to need to bump up the version.

**Comment by MaximeD** [comment]
Thanks, I'm looking forward for the new release!
