### ISSUE TITLE
Bump to 1.0.2

### ISSUE THREAD

**Issue by kayn1** [discourse/prometheus_exporter#215]
Hi @SamSaffron 
Could you update changelog and update version? 🙏 
We would like to use latest changes but not through referencing `main`

**Comment by yns01** [comment]
Bumping this one @SamSaffron, would be great to have a new release! Thanks!

**Comment by MaximeD** [comment]
Bumping on this one too as we would also love to have a new release! Thanks in advance

**Comment by yns01** [comment]
👋 @SamSaffron we would really grateful if you could release a new version. If you're concerned about breaking changes, we could mark it as a major one?

**Comment by davidtaylorhq** [comment]
Given the breaking changes, we've bumped to `2.0.0` via https://github.com/discourse/prometheus_exporter/commit/6099df5baa50c9f99bdfa00c390330b14cf93273
