### ISSUE TITLE
ActiveRecord collector does not expose hostname by default

### ISSUE THREAD

**Issue by sosedoff** [discourse/prometheus_exporter#271]
AR Instrumentation exposes the `hostname` in https://github.com/discourse/prometheus_exporter/blob/main/lib/prometheus_exporter/instrumentation/active_record.rb#L57
but its not picked up in the collector: https://github.com/discourse/prometheus_exporter/blob/main/lib/prometheus_exporter/server/active_record_collector.rb#L28-L39

Is this behavior intentional?

**Comment by SamSaffron** [comment]
Interesting, no I do not think this is intentional.

**Comment by sosedoff** [comment]
I've discovered this issue while working on #268 refactor. I'll send a PR with a fix.
