### ISSUE TITLE
New Gem Release Request

### ISSUE THREAD

**Issue by benngarcia** [discourse/prometheus_exporter#297]
I've been using this gem for a bit and it's great! Any chance you can release a new version to ruby gems? It's just a bit nicer to be able to reference versions instead of commit hashes in our Gemfile.

As far as I can see, the latest version release was Jan 2023, and since then we've gotten quite a few goodies like support for [GoodJob instrumentation](https://github.com/discourse/prometheus_exporter/commit/8d77c53333b5793f26d8e90bbeecdab850acc3f8), but I don't see a release with these additions. 

Thanks for all the work you've done with this project!

**Comment by SamSaffron** [comment]
thanks, in the oven, should be released today.
