### ISSUE TITLE
Question: where would I implement application-specific counters/gauges? (e.g. number of registered users)

### ISSUE THREAD

**Issue by siebertm** [discourse/prometheus_exporter#3]
first: thank you for this project.

I have a question regarding custom metrics and where to "observe" them: when I want to have a gauge `users_total`, this is usually just a `User.count`, so it will be directly read from the database and is not triggered by any http request to the main application.

How would I set this up? I see how I can create a custom metric, but I only see how to use `send_json` based on a http request. 
Should I create a cron job which uses `send_json` every minute? Or is there a nifty hook of some kind which i just didn't see yet?

**Comment by SamSaffron** [comment]
I updated the documentation per: https://github.com/discourse/prometheus_exporter/commit/55d7ddddc835df981d3e0eaea20ae49a1c9beacb 

Does this cover it?

**Comment by siebertm** [comment]
Yes, thank you!

Although this leads to a warning message `Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394` because rails boots before the exporter is running.

I assume this is safe to ignore?

**Comment by SamSaffron** [comment]
Yes but I think we should do a separate topic to hold off on that logging
for 20-30 secs to allow for this

**Comment by SamSaffron** [comment]
Yes, safe to ignore cause we actually buffer the messages and then send them when it is able to connect (capped) 

We should probably amend it so we only log if we are forced

**Comment by nylen** [comment]
@SamSaffron I am not sure what is the best place to report this, but I also see this error a bunch of times when running unit tests for a Discourse plugin (locally or on Travis).

For example: https://travis-ci.org/discourse/discourse-chat-integration/builds/553106999

**Comment by SamSaffron** [comment]
Discourse related stuff really belongs on meta.discourse.org ...
