### ISSUE TITLE
Docker image not built for latest release

### ISSUE THREAD

**Issue by sosedoff** [discourse/prometheus_exporter#301]
Looks like the docker image build was skipped per https://github.com/discourse/prometheus_exporter/actions/runs/7441197605

Not sure exactly why, but do you think it'll be possible to publish the amd64/arm64 images manually?
Maybe have an option to trigger publish action instead of waiting for a new gem release.

**Comment by SamSaffron** [comment]
honestly I am not sure at all, I did not build this part, not even sure how
it is all wired.
