### ISSUE TITLE
Using Custom Collector Error (Can't find class ... CollectorBase)

### ISSUE THREAD

**Issue by mbowen** [discourse/prometheus_exporter#35]
Is there a bug using a custom collector? I get this when try to use one:

    $ prometheus_exporter -v -c custom_collector.rb
        [Error] Can not find a class inheriting off PrometheusExporter::Server::CollectorBase

Looking at bin/prometheus_exporter script, it looks like we need to set the
found flag when we find the custom collector iterating over the class objects.
Indeed, server seems to work just fine if I add this.

Trimmed down collector.

file: custom_collecor.rb

    class CustomCollector < PrometheusExporter::Server::CollectorBase
    def initialize
        @verified_users_cnt = PrometheusExporter::Metric::Counter.new('verified_users_count', 'Total # of verified accounts')
        @mutex = Mutex.new
    end

    def process(str)
        obj = JSON.parse(str)
        @mutex.synchronize do
        if verified_cnt = obj["VERIFIED_USERS_COUNT"]
            @verified_users_cnt.observe(verified_cnt)
        end
        end
    end

    def prometheus_metrics_text
        @mutex.synchronize do
        "#{@verified_users_cnt.to_prometheus_text}\n"
        end
    end
end

Thank you for creating this project! This precisely solves the problem I had
with forked puma workers and unpredictable count results using the official
Prometheus client for ruby -- frustrating for sure, aargh.

  if custom_collector_filename
    eval File.read(custom_collector_filename), nil, File.expand_path(custom_collector_filename)
    found = false

    base_klass = PrometheusExporter::Server::CollectorBase

    ObjectSpace.each_object(Class) do |klass|
      if klass < base_klass && klass != base_klass
        options[:collector_class] = klass
        found = true
      end
    end

    if !found
      STDERR.puts "[Error] Can not find a class inheriting off PrometheusExporter::Server::CollectorBase"
      exit 1
    end
  end
  ...

**Comment by SamSaffron** [comment]
Yes good catch, this is a bug, do you mind doing a PR here to fix it? I can push a new release out there.

**Comment by mbowen** [comment]
Sure. https://github.com/discourse/prometheus_exporter/pull/36

**Comment by SamSaffron** [comment]
excellent ... doing a new release now
