### ISSUE TITLE
require 'prometheus_exporter/client' returns NameError

### ISSUE THREAD

**Issue by sumanp** [discourse/prometheus_exporter#37]
While integrating with  a sinatra app
require 'prometheus_exporter/client' and 'prometheus_exporter/instrumentation' returns NameError witht the following trace.

<code>
~/some_app: rackup config.ru -o 0.0.0.0

W, [2018-10-05T12:13:49.188002 #3224]  WARN -- : Overwriting existing field name in class User.
/Users/pi/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/prometheus_exporter-0.3.4/lib/prometheus_exporter/client.rb:6:in `<top (required)>': uninitialized constant PrometheusExporter (NameError)
</code>

I tried `require 'prometheus_exporter'` to fix this issue. However, the default metric counters are all zero. Any way to fix this?

<pre><code>
 HELP ruby_collector_working Is the master process collector able to collect metrics
 TYPE ruby_collector_working gauge
ruby_collector_working 0

 HELP ruby_collector_rss total memory used by collector process
 TYPE ruby_collector_rss gauge
ruby_collector_rss 0

 HELP ruby_collector_metrics_total Total metrics processed by exporter web.
 TYPE ruby_collector_metrics_total counter
ruby_collector_metrics_total 0

 HELP ruby_collector_sessions_total Total send_metric sessions processed by exporter web.
 TYPE ruby_collector_sessions_total counter
ruby_collector_sessions_total 0

 HELP ruby_collector_bad_metrics_total Total mis-handled metrics by collector.
 TYPE ruby_collector_bad_metrics_total counter
ruby_collector_bad_metrics_total 0
</code></pre>

**Comment by Eric-Fontana-Bose** [comment]
You need to add these 2:


```ruby
require 'prometheus_exporter'
require 'prometheus_exporter/client'
```

**Comment by david-harkness** [comment]
In additional to the above two.  I have to add
```ruby
require 'prometheus_exporter/instrumentation'
```
