### ISSUE TITLE
is auth supported?

### ISSUE THREAD

**Issue by IgorPolyakov** [discourse/prometheus_exporter#52]
I would like to use basic authentication to protect metrics from outsiders

**Comment by SamSaffron** [comment]
In general people keep the port for prometheus without auth and never export it to the public net. You have a few options here if you really want basic auth

1. Inherit off our WebServer class and implement it there. 

2. Write simple middleware that implements metrics like this: https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/server/web_server.rb#L114-L147 and then mount basic auth middleware in front

3. Run traffic via proxy that adds basic auth.

**Comment by IgorPolyakov** [comment]
Thank you, there are no more questions) I will close issuse
