### ISSUE TITLE
Process metrics get lost on docker/kubernetes environments

### ISSUE THREAD

**Issue by codez** [discourse/prometheus_exporter#53]
We use prometheus_exporter in a kubernetes deployment where multiple containers (puma, delayed_job, ..) report to the same exporter. In this environment, it is common that the main processes in the different containers all get PID 1.

Because of https://github.com/discourse/prometheus_exporter/blob/fb41e20d6fe800ca86ce16b395ad6c1256228b3b/lib/prometheus_exporter/server/process_collector.rb#L65, only one set of process metrics may exist per PID. Hence, depending on which container reported last, we only see those process metrics. The ones of the other containers are lost.

I think a check on `(obj["pid"] == current["pid"] && obj["process_type"] == current["process_type"])` would resolve this issue, as we assign different `process_types` per container.

**Comment by SamSaffron** [comment]
I see what you mean, in general we keep a single collector per container, but if you want one collector for multiple containers ... yeah ... problems... 

Feel free to make a PR to fix it, make sure it is both tested and that you update the readme with some instructions!

**Comment by codez** [comment]
Ok, I will be able to work on a PR in a week or two.

By "a single collector per container", do you mean a dedicated exporter process/sidecar per container? Or did I miss an option to have multiple `ProcessCollector`s in one server (besides implementing a whole new `Collector`)?

**Comment by kevine-voicera** [comment]
@codez @SamSaffron Can you elaborate on the "single collector per container" mentioned here. Architecturally, should we pair up one collector as a sidecar for each container? Or can multiple containers effectively work?
