### ISSUE TITLE
Explicitly setting counter value

### ISSUE THREAD

**Issue by dpetersen** [discourse/prometheus_exporter#62]
I have a question about a change I'd like to make but wanted to check if it would even be accepted.

I'm trying to instrument our application's Sidekiq info. I want most of what's available from `Sidekiq::Stats`, like queue lengths and processed/failed. Queues are clearly gauges, but processed/failed seems more suitable for counters since they can be reset to zero in the Sidekiq UI but in reality are always increasing.

I can only get the current processed/failure count from Sidekiq, but the API for the `PrometheusExporter::Metric::Counter` only allows the count to be incremented. Unless I resort to `instance_variable_get`/`set` shenanigans or subclass the `PrometheusExporter::Metric::Base` myself, I don't think I can accomplish what I want. I would like to be able to set the value of a counter directly.

Neither the Ruby client nor the Golang client allows this, either, so perhaps I'm an idiot and instrumenting thing incorrectly.

Would you accept a PR to allow direct setting of a Counter's value, and if so what would be a reasonable method name? I was thinking:
```ruby
def reset(to = 0, labels = {})
  # blah
end
```

Thanks for this gem. It took a while to wrap my head around how to run it in our Kubernetes environment, but the architecture works great and improves upon our old solution.

**Comment by SamSaffron** [comment]
Yeah ability to reset a Counter via api sounds fine to me.
