### ISSUE TITLE
Instrument unicorn server out of the box

### ISSUE THREAD

**Issue by siebertm** [discourse/prometheus_exporter#64]
If we had a server instrumentation for unicorn - which works almost the same as the puma instrumentation - would you be willing to consider that for merging? 

I'd have one "ready" in our code base, and we could prepare this for merging in if you'd approve of that feature.

Thanks already!

**Comment by SamSaffron** [comment]
As long as it is optional and free when not used then sure. 

You talking about raindrops or something else? What are the specifics?

**Comment by siebertm** [comment]
Yeah, I've been using raindrops for socket listener stats + some static "how many worker processes are configured". I was not able to get this autmatically.

BUT i noticed that i broke something on our staging env, gotta see what happened.
