### ISSUE TITLE
Label values not being escaped properly

### ISSUE THREAD

**Issue by tjhorner** [discourse/prometheus_exporter#66]
Our statistics stopped working for absolutely no reason (we changed nothing):

<img width="358" alt="image" src="https://user-images.githubusercontent.com/2646487/55675131-f9161200-5872-11e9-89f0-48b01b302cd6.png">

So I took a look at the Prometheus error log and I see this:

```
level=warn ts=2019-04-06T20:45:43.810524544Z caller=scrape.go:867 component="scrape manager" scrape_pool=redacted target=http://our-host-that-serves-the-exporter/metrics msg="append failed" err="expected label name, got \"INVALID\""
```

It turns out the response that the `prometheus_exporter` gem was generating did not escape the label values:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/2646487/55675146-38dcf980-5873-11e9-82d9-328b318ce485.png">

Thus, Prometheus failed to parse the metrics response and stopped working entirely.

I'm not sure what else besides quotes and line breaks should be escaped, but in the meantime I just wrote a simple method to escape quotes and replace them with `\"`.

**Comment by SamSaffron** [comment]
yeah we got to do some escaping here, will add something in.
