### ISSUE TITLE
Version 0.4.8 is broken

### ISSUE THREAD

**Issue by paho-outreach** [discourse/prometheus_exporter#67]
Just running `require prometheus_metrics/server` raises an error due to a missing `begin`/`end` in the loop here: https://github.com/discourse/prometheus_exporter/blob/8623ab626c6d41c94b37294673a1657a54ec4a9c/lib/prometheus_exporter/instrumentation/unicorn.rb#L14-L21

This is using Ruby version 2.4.5p335.

**Comment by SamSaffron** [comment]
I have a feeling this is ruby version related, what are you on?

Should be easy to fix will do another gem shortly

**Comment by paho-outreach** [comment]
Sorry, I thought about that too late and added my version in an edit; 2.4.5.

**Comment by SamSaffron** [comment]
Apologies, pushed 0.4.9 to fix the issue!

**Comment by paho-outreach** [comment]
Thanks!
