### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by zbelzer** [discourse/prometheus_exporter#81]
Following the instructions in the README for per-process stats:

```ruby
after_fork do
  require 'prometheus_exporter/instrumentation'
  PrometheusExporter::Instrumentation::Process.start(type:"web")
end
```

I first received `uninitialized constant PrometheusExporter (NameError)`

And then once I added `require 'prometheus_exporter'`

I got `uninitialized constant PrometheusExporter::Client (NameError)`

So I could add  `require 'prometheus_exporter/client'`

But this seems silly. Should the files be updated to require their own dependencies or am I doing something totally wrong here?

**Comment by SamSaffron** [comment]
I hear you, but I kind of resisted autoloading here and was trying to keep stuff as slim as possible. There is a balancing act here.

**Comment by zbelzer** [comment]
I wasn't thinking auto loading, just requiring client in process.rb and the root module in others. If you're meant to require things a la carte, then they should bring with them their own dependencies.

Again, or I'm missing something about how the library is intended to be loaded.

**Comment by SamSaffron** [comment]
Any chance you can do a PR of your proposed change here?

**Comment by zbelzer** [comment]
Clearly I got distracted, but this was it: https://github.com/discourse/prometheus_exporter/commit/3614e77f3b3a8039d6f46a440395911e3f6861dc
