### ISSUE TITLE
Why counters has a decrement method?

### ISSUE THREAD

**Issue by ahmgeek** [discourse/prometheus_exporter#82]
According to Prometheus [client writing](https://prometheus.io/docs/instrumenting/writing_clientlibs/) document:
**Counters**,  **MUST NOT** allow the value to decrease.

However the implementation of the counter breaks this rule: 

https://github.com/discourse/prometheus_exporter/blob/92496a15211ee0a796e8f4b85420870e76f54638/lib/prometheus_exporter/metric/counter.rb#L32-L35

Any reason for this?

**Comment by SamSaffron** [comment]
Well honestly I am not sure, we should probably remove this line, I agree
it can cause confusion.

Sometimes we act as a forwarder so we need to "reset" so our numbers remain
in sync, but I can not think of a reason to decrement.

**Comment by ahmgeek** [comment]
@SamSaffron sense we are at it, the Document also mentioned that Counter only has `increment` method, why `observe`?

**Comment by paveltyk** [comment]
I'm confused with `decrement` for counter as well.
