### ISSUE TITLE
use standard logging for errors instead of STDERR

### ISSUE THREAD

**Issue by kleinron** [discourse/prometheus_exporter#83]
If the target server is not accessible to the client, the following message repeats itself in STDERR:
```
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394
```
(the actual host and port might change, of course).

This outcome causes the standard error to be flooded with error messages.

Perhaps there's a way to inject either a stream object (with the same API as STDERR/STDOUT) or a logger object so that the hosting application could control the logging?

**Comment by dorongutman** [comment]
Yes please, we are running a few environments without the server part (for example - a console) and in those cases there's no need for the prometheus exporter server, but it's impossible to work with these error messages.

I also think that there should be an option to disable the endless retry loop if the server isn't available. Maybe a configurable max retry attempts?

**Comment by SamSaffron** [comment]
Sure. Happy to play with the delay here and to introduce a pluggable logger if anyone wants to try it out. This could be a warn and you could only be interested in errors.
