### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dg-fiduciagad** [discourse/prometheus_exporter#89]
Hello prometheus_exporter maintainers,

would you mind to release a new version of the "prometheus_exporter"? #86 added a feature which I'm interested in. For now I use the git repository in my "bundler" spec, but I would love to get back to a version number.

Thanks a lot.

Cheers
Dennis

**Comment by SamSaffron** [comment]
No probs, just pushed a new release!

**Comment by vijayanandnandam** [comment]
@SamSaffron can you create a new release? I want to use the activerecord collector

**Comment by SamSaffron** [comment]
No problem, new release is out! Thanks heaps.
