### ISSUE TITLE
Unable to aggregate web metrics due to use of summary

### ISSUE THREAD

**Issue by ball-hayden** [discourse/prometheus_exporter#92]
More of a question about design decisions rather than a bug, but sort of a bug.

As it stands, the web collector defines summary metrics for durations.

As noted in the Prometheus documentation, summary metrics can't be correctly aggregated across multiple labels (the main use case here being across multiple servers).

I'm wondering why summary metrics are used here instead of histogram metrics - the latter would allow the correct aggregation of statistics between servers (allowing calculation of overall percentiles etc)?

**Comment by SamSaffron** [comment]
We implement summary very differently to how the prometheus gem implements it.

Our summary is not an estimate, it is the actual accurate value. If load is somewhat even between workers averaging the values give a very close estimate of what the value would be across instances.

The trouble with histogram aggregation is that you would need to pick all the perfect buckets to get an accurate picture of what the real median (or particular percentile) is. You are not going to make buckets for every single millisecond.

**Comment by ball-hayden** [comment]
Thank you. Statistics is not my strong point, so that really helps.

**Comment by tjohnell-handy** [comment]
> If load is somewhat even between workers averaging the values give a very close estimate of what the value would be across instances.

For a low throughput service, the average value for something like a 99th percentile could be wildly inaccurate. This goes back to the [blog post](https://latencytipoftheday.blogspot.de/2014/06/latencytipoftheday-you-cant-average.html) linked within the [Prometheus documentation](https://prometheus.io/docs/practices/histograms/).

In terms of picking perfect buckets, when it comes to defining SLOs, those buckets could be pre-determined. It's actually what the above documentation encourages the reader to do. E.G., if my SLO is 95% of requests are < 300 ms, I would just implement a bucket for 300ms.

The documentation within the SRE workbook by Google gives [many examples](https://sre.google/workbook/implementing-slos#measuring-the-slis) using the histogram type, so I was a bit saddened that I would not be able to use the metrics we have in production out-of-the-box.
