### ISSUE TITLE
Feature Request: ActiveRecord Connection Pool Stats

### ISSUE THREAD

**Issue by vijayanandnandam** [discourse/prometheus_exporter#93]
Hello,

Want to request instrumentation for collecting ActiveRecord connection pool stats.

Method to get stats is `ActiveRecord::Base.connection_pool.stat`. [Documentation here ](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-stat)

This has to be collected at worker level in cluster mode and at master level in single process mode.

**Comment by SamSaffron** [comment]
Sure, we collect this for Discourse. As long as it all responds I am fine to add the stat, send through a PR.

**Comment by vijayanandnandam** [comment]
Sent one.
