### ISSUE TITLE
Change default port 9493 on rails?

### ISSUE THREAD

**Issue by satriashp** [discourse/prometheus_exporter#97]
How can i change default port from rails integration to something like 9495 or 9396?
Cause i have multiple rails apps in one server.

Thanks.

**Comment by SamSaffron** [comment]
This is configurable have a look at the readme ... you have quite a few options. 

You can run multiple collectors on the same machine one per rails app

You can run a single collector for multiple rails app

You can run in single process mode 

Lots of options!

**Comment by lawitschka** [comment]
You can overwrite the default client being used by the Rails middleware:

```
PrometheusExporter::Client.default = PrometheusExporter::Client.new(
    host: ENV.fetch('PROMETHEUS_EXPORTER_HOST'),
    port: ENV.fetch('PROMETHEUS_EXPORTER_PORT')
  )
```
